server:
  port: 8091
spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3307/db_products
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  pattern:
    console: "%d{HH:mm:ss} [%t] %-5level %logger{36} - %msg%n"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/